---
- name: "Enable and run Puppet agent"
  hosts: dev
  
  tasks:
    - name: Enable puppet
      command: /opt/puppetlabs/puppet/bin/puppet agent --enable
      become: true
      become_user: root
      become_method: sudo
    - name: Run puppet
      command: /opt/puppetlabs/puppet/bin/puppet agent -t
      become: true
      become_user: root
      become_method: sudo
    - name: Run puppet again
      command: /opt/puppetlabs/puppet/bin/puppet agent -t
      become: true
      become_user: root
      become_method: sudo