---
- name: "Enable and run Puppet agent"
  hosts: dev
  become: true
  become_method: sudo
  tasks:
    - name: Enable puppet
      command: /usr/bin/sudo /opt/puppetlabs/puppet/bin/puppet agent --enable
      become: true
      become_method: sudo
    - name: Run puppet
      command: /usr/bin/sudo /opt/puppetlabs/puppet/bin/puppet agent -t
      become: true
      become_method: sudo
    - name: Run puppet again
      command: /usr/bin/sudo /opt/puppetlabs/puppet/bin/puppet agent -t
      become: true
      become_method: sudo