---
- name: "Enable and run Puppet agent"
  hosts: dev
  become: true
  tasks:
    - name: Enable puppet
      shell: /opt/puppetlabs/puppet/bin/puppet agent --enable
    - name: Run puppet
      shell: /opt/puppetlabs/puppet/bin/puppet agent -t
    - name: Run puppet again
      shell: /opt/puppetlabs/puppet/bin/puppet agent -t