---
- name: "Enable and run Puppet agent"
  hosts: dev
  
  tasks:
    - name: Enable puppet
      shell: puppet agent --enable
      become: true
      become_user: root
      become_method: sudo
    - name: Run puppet
      shell: puppet agent -t
      become: true
      become_user: root
      become_method: sudo
    - name: Run puppet again
      shell: puppet agent -t
      become: true
      become_user: root
      become_method: sudo