---
- name: "Enable and run Puppet agent"
  hosts: dev
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Enable puppet
      command: /opt/puppetlabs/puppet/bin/puppet agent --enable
    - name: Run puppet
      command: /opt/puppetlabs/puppet/bin/puppet agent -t
    - name: Run puppet again
      command: /opt/puppetlabs/puppet/bin/puppet agent -t